INSERT INTO company (name, srn, email, logo, address_id) VALUES ('Vilnohirsk Mining Metallurgical Plant', 121345, 'Vilnohirsk@gmail.com', null, 1); 
INSERT INTO company (name, srn, email, logo, address_id) VALUES ('Podolsky Smak', 122345, 'PodolskySmak@gmail.com', null, 2); 
INSERT INTO company (name, srn, email, logo, address_id) VALUES ('Econom-servis Gp CffInfo', 123345, 'EconomservisGp@gmail.com', null, 3); 
INSERT INTO company (name, srn, email, logo, address_id) VALUES ('Epcf Syaivo LtdInfo', 124345, 'EpcfSyaivo@gmail.com', null, 4); 
INSERT INTO company (name, srn, email, logo, address_id) VALUES ('Planet Service', 125345, 'PlanetService@gmail.com', null, 5); 
INSERT INTO company (name, srn, email, logo, address_id) VALUES ('Global Titan Distribution Inc', 126345, 'GlobalTitan@gmail.com', null, 6); 
INSERT INTO company (name, srn, email, logo, address_id) VALUES ('Sea Electronics', 127345, 'SeaElectronics@gmail.com', null, 7); 
INSERT INTO company (name, srn, email, logo, address_id) VALUES ('Kaalbye Logistics Ltd', 128345, 'KaalbyeLogistics@gmail.com', null, 8); 
INSERT INTO company (name, srn, email, logo, address_id) VALUES ('Energy Xxii', 129345, 'EnergyXxii@gmail.com', null, 9); 
INSERT INTO company (name, srn, email, logo, address_id) VALUES ('Eurocom Components', 120345, 'EurocomComponents@gmail.com', null, 10); 
INSERT INTO company (name, srn, email, logo, address_id) VALUES ('Natural Foods', 102345, 'NaturalFoods@gmail.com', null, 11); 
INSERT INTO company (name, srn, email, logo, address_id) VALUES ('Cory Sro', 112345, 'CorySro@gmail.com', null, 12); 
INSERT INTO company (name, srn, email, logo, address_id) VALUES ('Polymercontainer Plant', 122345, 'PolymerPlant@gmail.com', null, 13); 
INSERT INTO company (name, srn, email, logo, address_id) VALUES ('Xado Corp', 132345, 'XadoCorp@gmail.com', null, 14); 
INSERT INTO company (name, srn, email, logo, address_id) VALUES ('Garbuz Studio', 142345, 'GarbuzStudio@gmail.com', null, 15); 
